<a href="https://colab.research.google.com/github/sily3586/ai-security/blob/master/5th_week/Hyeok_min.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=100
print(a)

100


In [3]:
sum=0
for i in range(1,11):
  sum +=i
print(sum)

55


In [4]:
treeHit = 0
while treeHit < 10:
  treeHit += 1
  print("나무를 %d번 찍었습니다." %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다.")

나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무가 넘어갑니다.


In [9]:
class calculator:
  def __init__(self):
    self.result = 0

  def add(self, a, b):
    self.result = a + b
    return self.result
  
  def minus(self, a, b):
    return self.result

  cal = calculator()

  print(cal.add(4,5))
  print(cal.minus(3,9))

NameError: ignored

In [0]:
import torch

In [12]:
x = torch.empty(5,3)
print(x)

tensor([[1.7426e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [13]:
x = torch.rand(5,3)
print(x)

tensor([[0.2134, 0.7952, 0.2002],
        [0.8038, 0.1563, 0.5079],
        [0.2732, 0.8607, 0.6288],
        [0.7593, 0.3814, 0.7322],
        [0.4375, 0.0764, 0.5252]])


In [14]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.2117, 0.3454, 0.7055, 0.6264],
        [0.8499, 0.7199, 0.4880, 0.1489],
        [0.9214, 0.4519, 0.7955, 0.5441]])
tensor([[0.0881, 0.1713, 0.0387, 0.7397],
        [0.7413, 0.1344, 0.1212, 0.3685],
        [0.3544, 0.4286, 0.7823, 0.9942]])
tensor([[0.2997, 0.5167, 0.7442, 1.3661],
        [1.5912, 0.8543, 0.6093, 0.5174],
        [1.2758, 0.8805, 1.5778, 1.5383]])
