<a href="https://colab.research.google.com/github/devahws/ai-security/blob/master/5th%20week/%205th%20week_WOOSEONG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!ls

sample_data


In [2]:
!pwd

/content


In [5]:
import os
os.chdir('/content/drive/My Drive')

FileNotFoundError: ignored

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
os.chdir('/content/drive/My Drive/ai-security')

In [10]:
sum =0 
for i in range(10):
  sum+=i
  print(sum)

0
1
3
6
10
15
21
28
36
45


In [11]:
class calculator:
  def __init__(self):
    self.result =0

  def add(self, a, b):
    self.result = a+b
    return self.result

  def minus(self, a, b):
    self.result = a-b
    return self.result

cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [12]:
def HowToGo(money):
  if money > 5000:
    print("택시를 타고 가자!")
  elif money > 1250:
    print("대중교통을 이용하자!")
  else:
    print("걸어가자")

HowToGo(1000)

걸어가자


In [0]:
import os
os.chdir('/content/drive/My Drive/ai-security')

In [14]:
!pwd

/content/drive/My Drive/ai-security


In [0]:
import torch

In [0]:
import os
os.chdir('/content/drive/My Drive/ai-security/ai-security')

In [17]:
!pwd

/content/drive/My Drive/ai-security/ai-security


In [19]:
x = torch.empty(5,3)
print(x)

tensor([[2.5846e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3236e+22, 1.6764e+22, 1.0812e-05],
        [8.1717e+20, 8.2726e+20, 1.0478e+21],
        [3.3245e+21, 2.0973e-07, 0.0000e+00]])


In [20]:
x = torch.empty(5,5)
print(x)

tensor([[2.8530e-36, 0.0000e+00, 6.8664e-44, 7.9874e-44, 6.3058e-44],
        [6.8664e-44, 6.7262e-44, 6.3058e-44, 6.7262e-44, 7.0065e-44],
        [1.1771e-43, 6.7262e-44, 7.1466e-44, 8.1275e-44, 7.4269e-44],
        [7.1466e-44, 8.1275e-44, 6.8664e-44, 7.7071e-44, 6.4460e-44],
        [7.8473e-44, 7.5670e-44, 7.9874e-44, 7.2868e-44, 7.4269e-44]])


In [21]:
x = torch.rand(5,3)
print(x)

tensor([[0.6245, 0.5303, 0.7817],
        [0.9222, 0.9586, 0.7229],
        [0.8489, 0.9570, 0.9065],
        [0.0185, 0.1296, 0.5636],
        [0.5284, 0.3770, 0.3648]])


In [22]:
y = torch.rand(5,3)
z = torch.add(x,y)
print(z)

tensor([[1.2962, 1.4805, 1.2324],
        [1.4009, 1.1862, 1.7142],
        [1.7655, 1.3606, 1.4700],
        [0.9192, 0.5164, 0.7262],
        [1.4106, 1.1746, 0.5437]])


In [23]:
git remote add upstream https://github.com/tjdghks994/ai-security.git

SyntaxError: ignored