<a href="https://colab.research.google.com/github/choe1842/ai-security/blob/master/5th%20week/5th%20class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
dic_array = {1:"first", 2:"second", 3:"third"}
print(dic_array)

{1: 'first', 2: 'second', 3: 'third'}


In [4]:
treehit = 0
while treehit < 10:
  treehit += 1
  print("나무를 %d번 찍었습니다" %treehit)
  if treehit == 10:
    print("나무가 넘어갑니다~~")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다~~


In [5]:
def HowToGo(money):
  if money >= 5000:
    print("택시 타")
   
  elif money >= 1250:
    print("버스 타")
   
  else:
    print("걸어가")
    
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)
   

걸어가
버스 타
택시 타


In [6]:
class Cal:
    def __init__(self):
        self.result = 0
    def add(self, num):
        self.result += num
        return self.result
    def sub(self, num):
        self.result -= num
        return self.result

cal1 = Cal()
cal2 = Cal()

print(cal1.add(3))
print(cal1.add(10))
print(cal2.add(65))
print(cal2.add(9))
print(cal2.sub(65))


3
13
65
74
9


In [7]:
list_ary = [1,2,3,[4,5,6]]
print(list_ary[3][2])

6


In [9]:
import torch
x = torch.empty(5,3)
print(x)


tensor([[ 1.0122e-36,  0.0000e+00,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.2858e-39],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -1.0643e+15]])


In [10]:
x = torch.rand(5,3)
y = torch.rand(5,3)

print(x,y,sep="\n")
print(torch.add(x,y))

tensor([[0.6852, 0.7887, 0.0880],
        [0.1136, 0.7488, 0.5666],
        [0.5881, 0.6385, 0.9341],
        [0.0834, 0.7242, 0.8900],
        [0.2041, 0.4679, 0.8513]])
tensor([[0.9014, 0.6036, 0.9518],
        [0.5836, 0.7350, 0.3249],
        [0.7906, 0.9711, 0.2420],
        [0.2678, 0.5786, 0.1454],
        [0.4233, 0.5183, 0.1336]])
tensor([[1.5865, 1.3923, 1.0397],
        [0.6972, 1.4838, 0.8915],
        [1.3787, 1.6096, 1.1762],
        [0.3512, 1.3027, 1.0354],
        [0.6274, 0.9862, 0.9850]])
