<a href="https://colab.research.google.com/github/tjdghks994/ai-security/blob/master/5th%20week/5th%20tuto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
a = 100
print(a)

a = 10.54
print(a)

100
10.54


In [6]:
b = "this is string type"
print(b)

b = "a"
print(b)

this is string type
a


In [7]:
list_arry = [1,4,6,"abc", "ddg"]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [4]:
list_arry_2 = [5,2,list_arry]
print(list_arry_2)

[5, 2, [1, 4, 6, 'abc', 'ddg']]


In [8]:
tuple_arry = (3,5,2,"gdd")
print(tuple_arry)

(3, 5, 2, 'gdd')


In [9]:
del tuple_arry[0]

TypeError: ignored

In [12]:
dic_arry = {1:"first", 2:"second", "third":3}
print(dic_arry)

{1: 'first', 2: 'second', 'third': 3}


In [13]:
print(dic_arry[3])

KeyError: ignored

In [14]:
print(dic_arry["third"])

3


In [15]:
set_arry = set("heelo")
print(set_arry)

{'e', 'l', 'h', 'o'}


In [18]:
c = True
type(c)

bool

In [20]:
sum = 0
for i in range(10):
  sum += i
print(sum)

45


In [23]:
sum = 0
for i in range(1,11):
  sum += i
print(sum)

55


In [26]:
treeHit = 0
while treeHit < 10:
  treeHit += 1
  print("나무를 %d 번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 1 번 찍었습니다
나무를 2 번 찍었습니다
나무를 3 번 찍었습니다
나무를 4 번 찍었습니다
나무를 5 번 찍었습니다
나무를 6 번 찍었습니다
나무를 7 번 찍었습니다
나무를 8 번 찍었습니다
나무를 9 번 찍었습니다
나무를 10 번 찍었습니다
나무가 넘어갑니다


In [27]:
for j in list_arry_2:
  print(j)

5
2
[1, 4, 6, 'abc', 'ddg']


In [28]:
money = 1000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 2500
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

money = 10000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [30]:
def HowToGo(money):
  if money > 5000:
    print("택시를 타고 가자!")
  elif money > 1250:
    print("대중교통을 이용하자!")
  else:
    print("걸어가라...")
  
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)

걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [32]:
class calculator:
  def __init__(self):
    self.result = 0
  
  def add(self, a, b):
    self.result = a + b
    return self.result
  
  def minus(self, a, b):
    self.result = a - b
    return self.result

cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [0]:
import torch

In [34]:
x = torch.empty(5,3)
print(x)

tensor([[4.2270e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.9097e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.5873e-43]])


In [35]:
x = torch.rand(5,3)
print(x)

tensor([[0.7612, 0.3672, 0.0231],
        [0.9345, 0.3133, 0.5636],
        [0.6115, 0.3316, 0.1507],
        [0.3561, 0.5951, 0.7169],
        [0.7554, 0.1675, 0.1413]])


In [36]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [37]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [44]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.0266, 0.0575, 0.8003, 0.7753],
        [0.3712, 0.9329, 0.1884, 0.4338],
        [0.8430, 0.2664, 0.0196, 0.3357]])
tensor([[0.6738, 0.9447, 0.5878, 0.5238],
        [0.6168, 0.9187, 0.8523, 0.2031],
        [0.3903, 0.8315, 0.0796, 0.0283]])
tensor([[0.7004, 1.0022, 1.3880, 1.2991],
        [0.9880, 1.8516, 1.0407, 0.6369],
        [1.2333, 1.0979, 0.0992, 0.3640]])
