<a href="https://colab.research.google.com/github/tjdghks994/ai-security/blob/master/5th%20week/5th_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a = 100
print(a)

100


In [0]:
sum = 0 
for i in range(10):
  sum += i
  print(sum)

45


In [0]:
list_ary = [1,2,3,[4,5,6]]
print(list_ary[3][2])

6


In [0]:
x = torch.zero(5,3)
print(x)

AttributeError: ignored

In [0]:
import torch

In [0]:
x = torch.empty(5,3)

In [0]:
print(x)

tensor([[1.3303e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.9097e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.5873e-43]])


In [0]:
x = torch.rand(5,3)

In [0]:
y = torch.rand(5,3)

In [0]:
print(x,y,sep="\n")
print(torch.add(x,y))

tensor([[0.2070, 0.7149, 0.2719],
        [0.6347, 0.3362, 0.5248],
        [0.5506, 0.1865, 0.6972],
        [0.8311, 0.2920, 0.1257],
        [0.3560, 0.4882, 0.9862]])
tensor([[0.4892, 0.7167, 0.8941],
        [0.1527, 0.7263, 0.3918],
        [0.4668, 0.8687, 0.7185],
        [0.1798, 0.4231, 0.6740],
        [0.7115, 0.7832, 0.5034]])
tensor([[0.6962, 1.4316, 1.1659],
        [0.7874, 1.0625, 0.9166],
        [1.0174, 1.0552, 1.4158],
        [1.0109, 0.7151, 0.7997],
        [1.0676, 1.2714, 1.4896]])
