<a href="https://colab.research.google.com/github/seong-bin-yun/ai-security/blob/master/5th%20week/5weeks_seongbin_silsep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
a= 100
print(a)
a=10.54
print(a)

100
10.54


In [3]:
b="this is string type"
print(b)

b="a"
print(b)

this is string type
a


In [4]:
list_arry = [1,4,6,"abc", "ddg"]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [9]:
list_arry_2=[list_arry,5,2]
print(list_arry_2)

[[1, 4, 6, 'abc', 'ddg'], 5, 2]


In [10]:
tuple_arry = (3,5,2,"ggd")
print(tuple_arry)

(3, 5, 2, 'ggd')


In [11]:
del tuple_arry[0]

TypeError: ignored

In [12]:
dic_arry = {1: "first", 2: "second", "third" : 3}
print(dic_arry)

{1: 'first', 2: 'second', 'third': 3}


In [13]:
print(dic_arry[3])

KeyError: ignored

In [15]:
print(dic_arry["third"])
print(dic_arry[2])

3
second


In [16]:
set_arry = set("heelo")
print(set_arry)

{'h', 'l', 'e', 'o'}


In [17]:
c = True
type(c)

bool

In [18]:
sum = 0
for i in range(10):
  sum += i
  
print(sum)

45


In [19]:
sum=0
for i in range(1,11):
  sum+=i
print(sum)

55


In [23]:
treeHit=0
while treeHit <10 :
  treeHit +=1
  print("나무를 %d 번 찍었습니다" %treeHit)
  if treeHit ==10 :
    print("나무가 넘어간드아~")

나무를 1 번 찍었습니다
나무를 2 번 찍었습니다
나무를 3 번 찍었습니다
나무를 4 번 찍었습니다
나무를 5 번 찍었습니다
나무를 6 번 찍었습니다
나무를 7 번 찍었습니다
나무를 8 번 찍었습니다
나무를 9 번 찍었습니다
나무를 10 번 찍었습니다
나무가 넘어간드아~


In [24]:
for j in list_arry_2:
  print(j)

[1, 4, 6, 'abc', 'ddg']
5
2


In [25]:
money = 1000
if money >5000 :
  print("택시 타자!")
elif money >1250 :
  print("대중교통 타자!")
else:
  print("걸어가라..")

money = 2500
if money >5000 :
  print("택시 타자!")
elif money >1250 :
  print("대중교통 타자!")
else:
  print("걸어가라..")

money = 10000
if money >5000 :
  print("택시 타자!")
elif money >1250 :
  print("대중교통 타자!")
else:
  print("걸어가라..")

걸어가라..
대중교통 타자!
택시 타자!


In [28]:
def HowToGo(money) :
  if money >5000 :
    print("택시 타자!")
  elif money >1250 :
    print("대중교통 타자!")
  else:
    print("걸어가라..")
  
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)

걸어가라..
대중교통 타자!
택시 타자!


In [29]:
class calculator:
  def __init__(self):
    self.result = 0
    
  def add(self,a,b):
    self.result = a+b
    return self.result
  def minus(self, a, b):
    self.result = a-b
    return self.result
  
cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [30]:
print(list_arry[3][2])

c


In [0]:
import torch

In [0]:
t = torch

In [35]:
x= t.empty(5,3)
print(x)

tensor([[8.3805e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 9.8439e-12],
        [6.5922e-10, 6.5643e-07, 8.1996e-10],
        [5.2358e+22, 1.6876e-07, 4.2052e-05],
        [4.2194e-08, 4.4203e-05, 1.8269e+34]])


In [40]:
x = t.rand(5,3)
print(x)

tensor([[0.6330, 0.2104, 0.0762],
        [0.5818, 0.5085, 0.8963],
        [0.6602, 0.3170, 0.0613],
        [0.4115, 0.8763, 0.2247],
        [0.1993, 0.1235, 0.6995]])


In [38]:
x= t.zeros(5,3,dtype = t.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [41]:
x = t.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [42]:
x= t.rand(3,4)
y= t.rand(3,4)
z= t.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.6464, 0.0294, 0.2148, 0.7845],
        [0.3392, 0.5315, 0.6172, 0.0592],
        [0.1882, 0.4660, 0.9686, 0.6285]])
tensor([[0.0173, 0.5721, 0.3355, 0.4938],
        [0.8204, 0.3040, 0.0092, 0.4065],
        [0.7679, 0.2461, 0.3362, 0.1633]])
tensor([[0.6637, 0.6016, 0.5503, 1.2783],
        [1.1596, 0.8355, 0.6264, 0.4656],
        [0.9562, 0.7121, 1.3048, 0.7918]])
