<a href="https://colab.research.google.com/github/ichwoni/ai-security-1/blob/master/5th%20week/chaewon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a=100
print(a)
a=10.54
print(a)

100
10.54


In [0]:
dic = {"k1":"v1", "k2":"v2", "k3":"v3"}
print(dic["k1"])

v1


In [0]:
class calculator:
  def __init__(self):
    self.result = 0
  def add(self,a,b):
    self.result = a+b
    return self.result
  def minus(self,a,b):
    self.result=a-b
    return self.result

cal = calculator()

print(cal.add(4,5))
print(cal.minus(100,3))

9
97


In [0]:
for i in range (10):
  for j in range (1, i, 1):
    print("*", end="")
  print("\n")





*

**

***

****

*****

******

*******

********



In [0]:
import torch

In [0]:
x=torch.empty(5,3)
print(x)

tensor([[1.1481e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 9.8439e-12],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.8269e+34]])


In [0]:
x=torch.rand(5,3)
print(x)

tensor([[0.9949, 0.9399, 0.0961],
        [0.3255, 0.9031, 0.7327],
        [0.2721, 0.9334, 0.7812],
        [0.1758, 0.0934, 0.8089],
        [0.8890, 0.8768, 0.8714]])


In [0]:
x=torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x=torch.rand(3,4)
y=torch.rand(3,4)
z=torch.add(x,y)

print(x,y,z, sep="\n")


tensor([[0.8102, 0.9069, 0.3061, 0.3704],
        [0.9025, 0.8251, 0.6876, 0.8874],
        [0.3098, 0.8112, 0.9237, 0.4250]])
tensor([[0.5042, 0.8410, 0.5736, 0.8225],
        [0.1577, 0.8683, 0.2395, 0.8954],
        [0.0073, 0.0359, 0.0339, 0.7136]])
tensor([[1.3144, 1.7479, 0.8798, 1.1929],
        [1.0603, 1.6934, 0.9271, 1.7828],
        [0.3171, 0.8471, 0.9576, 1.1386]])
