In [1]:
  a= 100
  print(a)
  
  a = 10.54
  print(a)

100
10.54


In [2]:
dic_arry = {1:"first", 2:"second", "third":3}
print(dic_arry[3])

KeyError: ignored

In [3]:
print(dic_arry["third"])

3


딕셔너리는 검색할 때 밸류 값 검색x 키 값으로 검색

In [4]:
set_arry = set("hello")
print(set_arry)

{'o', 'l', 'e', 'h'}


In [6]:
c = True
type(c)

bool

In [7]:
sum = 0
print(sum)

0


변수 초기화, 0.xxxx 쓰레기 값 들어있어서 해줘야 됨

In [10]:
sum=0
for i in range(1,11):
  sum +=i
print(sum)

55


In [12]:
treeHit = 0
while treeHit <10:
  treeHit += 1
  print("나무를 %d번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다


In [18]:
list_arry = [1,4,6,"abc","ddg"]
list_arry_2 = [5,4,list_arry]
print(list_arry_2[2][3])

for j in list_arry_2:
  print(j)

abc
5
4
[1, 4, 6, 'abc', 'ddg']


In [14]:
class calculator:
  def __init__(self):
    self.result=0
  
  def add(self, a, b):
    self.result = a+b
    return self.result
  
  def minus(self, a, b):
    self.result = a-b
    return self.result
  
cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [16]:
money = 1000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 2500
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 10000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")  


걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [0]:
import torch

In [20]:
x = torch.empty(5,3)
print(x)

tensor([[3.2780e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.7233e-37],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.4668e-33]])


In [22]:
x = torch.rand(5,3)
print(x)
y = torch.rand(5,3)
print(x,y,sep = "\n")
print(torch.add(x,y))

tensor([[0.2477, 0.8664, 0.4159],
        [0.4049, 0.2345, 0.4545],
        [0.7241, 0.7696, 0.1909],
        [0.6912, 0.7845, 0.5628],
        [0.6154, 0.1747, 0.5911]])
tensor([[0.2477, 0.8664, 0.4159],
        [0.4049, 0.2345, 0.4545],
        [0.7241, 0.7696, 0.1909],
        [0.6912, 0.7845, 0.5628],
        [0.6154, 0.1747, 0.5911]])
tensor([[0.6377, 0.0759, 0.8595],
        [0.4951, 0.0983, 0.9090],
        [0.9616, 0.8268, 0.2676],
        [0.9928, 0.3290, 0.6830],
        [0.3118, 0.3311, 0.3500]])
tensor([[0.8854, 0.9423, 1.2753],
        [0.9000, 0.3329, 1.3635],
        [1.6856, 1.5964, 0.4584],
        [1.6841, 1.1135, 1.2459],
        [0.9272, 0.5058, 0.9411]])
