<a href="https://colab.research.google.com/github/pgw0209/ai-security/blob/master/5th%20week/gyuwon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a = 100
print(a)

a = 10.54
print(a)

100
10.54


In [0]:
b = "this is string type"
print(b)

b = "a"
print(b)

this is string type
a


In [0]:
list_arry=[1,4,6,"abc", "ddg"]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [0]:
list_arry_2=[5,2,list_arry]
print(list_arry_2)

[5, 2, [1, 4, 6, 'abc', 'ddg']]


In [0]:
tuple_arry = (3,5,2,"add")
print(tuple_arry)

(3, 5, 2, 'add')


In [0]:
del tuple_arry[0]

TypeError: ignored

In [0]:
dic_arry={1:"first", 2:"second", "third":3}
print(dic_arry)

{1: 'first', 2: 'second', 'third': 3}


In [0]:
print(dic_arr[3])

NameError: ignored

In [0]:
print(dic_arry["third"])

NameError: ignored

In [0]:
set_arry = set("heelo")
print(set_arry)

{'e', 'l', 'o', 'h'}


In [0]:
c = True
type(c)

bool

In [0]:
sum = 0
for i in range(10):
  sum += i
print(sum)

45


In [0]:
sum = 0
for i in range(1, 11):
  sum += i
print(sum)

55


In [0]:
treeHit = 0
while treeHit < 10:
  treeHit += 1
  print("나무를 %d번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다


In [0]:
for j in list_arry_2:
  print(j)

5
2
[1, 4, 6, 'abc', 'ddg']


In [0]:
money = 1000
if money > 5000:
  print("택시를 타고가자!")
elif money >1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 2000
if money > 5000:
  print("택시를 타고가자!")
elif money >1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 10000
if money > 5000:
  print("택시를 타고가자!")
elif money >1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

걸어가라...
대중교통을 이용하자!
택시를 타고가자!


In [0]:
def HowToGo(money):
  if money > 5000:
    print("택시를 타고가자!")
  elif money >1250:
    print("대중교통을 이용하자!")
  else:
    print("걸어가라...")

HowToGo(1000) 
HowToGo(2500)
HowToGo(10000)

걸어가라...
대중교통을 이용하자!
택시를 타고가자!


In [0]:
class calculator:
  def __init__(self):
    self.result = 0
    
  def add(self, a, b):
      self.result = a+b
      return self.result
    
  def minus(self, a, b):
      self.result = a-b
      return self.result

cal = calculator()
  
print(cal.add(4, 5))
print(cal.minus(3, 9))

9
-6


In [0]:
import torch

In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.0754e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.8718, 0.1084, 0.8864],
        [0.1976, 0.9943, 0.6262],
        [0.6891, 0.9897, 0.7087],
        [0.2424, 0.8455, 0.6418],
        [0.9242, 0.1146, 0.4074]])


In [0]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.5710, 0.1499, 0.6748, 0.1028],
        [0.8740, 0.9960, 0.9115, 0.5602],
        [0.6158, 0.6295, 0.6566, 0.2063]])
tensor([[0.1902, 0.5835, 0.0832, 0.3614],
        [0.8737, 0.7457, 0.6959, 0.2170],
        [0.1819, 0.5353, 0.5318, 0.4212]])
tensor([[0.7611, 0.7335, 0.7580, 0.4642],
        [1.7478, 1.7416, 1.6074, 0.7772],
        [0.7977, 1.1648, 1.1884, 0.6275]])
