<a href="https://colab.research.google.com/github/hekoh99/ai-security/blob/master/5th%20week/Haeunko_5th_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
a = 100
print(a)

a = 10.54
print(a)

100
10.54


In [0]:
b = 'this is string type'
print(b)

b = 'a'
print(b)



this is string type
a


In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
list_arry = [1,4,6,"abc", "ddg"]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [0]:
list_arry2 = [5,2,list_arry]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [0]:
tuple_arry = (3,5,2,"gdd")
print(tuple_arry)

(3, 5, 2, 'gdd')


In [0]:
del tuple_arry[0]

TypeError: ignored

In [0]:
dic_arry = {1:"first", 2:"second", "third":3}
print(dic_arry)

{1: 'first', 2: 'second', 'third': 3}


In [0]:
print(dic_arry[3])

KeyError: ignored

In [0]:
print(dic_arry["third"])


3


In [0]:
set_arry = set("heelo")
print(set_arry)

{'h', 'o', 'l', 'e'}


In [0]:
c = True
type(c)

bool

In [0]:
sum = 0
for i in range(10):
  sum += i
print(sum)

45


In [0]:
sum = 0
for i in range(1,11):
  sum += i
print(sum)

55


In [0]:
treeHit = 0
while treeHit <10:
  treeHit += 1
  print("나무를 %d 번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")
  

나무를 1 번 찍었습니다
나무를 2 번 찍었습니다
나무를 3 번 찍었습니다
나무를 4 번 찍었습니다
나무를 5 번 찍었습니다
나무를 6 번 찍었습니다
나무를 7 번 찍었습니다
나무를 8 번 찍었습니다
나무를 9 번 찍었습니다
나무를 10 번 찍었습니다
나무가 넘어갑니다


In [0]:
for j in list_arry2:
  print(j)

5
2
[1, 4, 6, 'abc', 'ddg']


In [0]:
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[2.6855e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.7233e-37],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.4668e-33]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.5538, 0.7168, 0.2828],
        [0.0690, 0.6378, 0.9056],
        [0.3023, 0.0840, 0.2205],
        [0.7330, 0.5286, 0.9989],
        [0.5239, 0.5825, 0.9847]])


In [0]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5,3])
print(x)


tensor([5.5000, 3.0000])


In [0]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.5533, 0.8060, 0.6283, 0.2839],
        [0.8188, 0.9486, 0.0872, 0.3410],
        [0.6231, 0.9142, 0.8028, 0.0272]])
tensor([[0.5527, 0.7259, 0.1559, 0.0022],
        [0.3766, 0.4018, 0.3022, 0.5408],
        [0.8655, 0.1709, 0.7044, 0.6192]])
tensor([[1.1060, 1.5320, 0.7842, 0.2861],
        [1.1954, 1.3503, 0.3894, 0.8818],
        [1.4886, 1.0851, 1.5071, 0.6464]])
