In [2]:
treeHit = 0;
while treeHit < 10:
  treeHit += 1
  print("나무를 %d번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다


In [8]:
dic_arr = {1:'A', 2:'B', 'C':3}
print(dic_arr['C'])
print(dic_arr)

3
{1: 'A', 2: 'B', 'C': 3}


In [9]:
class calculator:
  def __init__(self):
    self.result = 0

  def add(self, a, b):
    self.result = a + b
    return self.result
  
  def minus(self, a, b):
    self.result = a - b
    return self.result

cal = calculator()
print(cal.add(5, 10))
print(cal.minus(25, 85))

15
-60


In [0]:
import torch

In [12]:
x = torch.empty(5,3)
print(x)

tensor([[1.1255e-35, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3108e-08, 2.6284e-06, 2.6852e-06],
        [3.2916e-09, 1.7157e-07, 6.5261e-10],
        [1.3445e+22, 1.0490e-08, 0.0000e+00]])


In [14]:
x = torch.rand(5, 3)
print(x)

y = torch.zeros(5, 3, dtype = torch.long)
print(y)

tensor([[0.8376, 0.1479, 0.8819],
        [0.6018, 0.0669, 0.9384],
        [0.2201, 0.1335, 0.3568],
        [0.2115, 0.3707, 0.6824],
        [0.1815, 0.6770, 0.1119]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.5399, 0.4285, 0.2987, 0.0748],
        [0.2493, 0.0451, 0.7993, 0.0961],
        [0.4090, 0.0020, 0.0597, 0.8691]])
tensor([[0.8804, 0.1218, 0.6240, 0.2808],
        [0.4174, 0.2606, 0.4292, 0.5655],
        [0.4711, 0.9156, 0.7007, 0.4545]])
tensor([[1.4203, 0.5502, 0.9227, 0.3557],
        [0.6667, 0.3057, 1.2285, 0.6616],
        [0.8800, 0.9176, 0.7604, 1.3235]])
