In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
os.chdir('drive/My Drive/ai-sec/ai-security/5th week')

In [0]:
!ls
!pwd

'5th ppt.pptx'	  '5th tuto.txt'      tensor_tutorial.ipynb
'5th tuto.ipynb'  'pytorch tuto.py'
/content/drive/My Drive/ai-sec/ai-security/5th week


# Pytuto 시작



## 1. 숫자형, 문자형 변수 입력 및 출력

In [0]:
a = 100
print(a)

a = 10.54
print(a)

b = "this is string type"
print(b)

b = "a"
print(b)

100
10.54
this is string type
a


## 2. 배열 입력 및 출력 

- list_arry (숫자, 문자 등을 사용한 배열)
- tuple_arry (삭제 및 수정이 불가능한 배열)

In [35]:
list_arry = [1, 4, 6, "abc", "ddg"]
print(list_arry)

del list_arry[0]

list_arry_2 = [5, 2, list_arry]
print(list_arry_2)
print(list_arry_2[2][1])

tuple_arry = (3, 5, 2, "gdd")
print(tuple_arry)

del tuple_arry[0]

[1, 4, 6, 'abc', 'ddg']
[5, 2, [4, 6, 'abc', 'ddg']]
6
(3, 5, 2, 'gdd')


TypeError: ignored

## 3. 특수 배열 입력 및 출력

- dic_arry (1:1(Key:Value) 대응이 되는 배열)
- set_arry (교, 차, 합집합을 위한 배열)


In [0]:
dic_arry = {1:"first", 2:"second", "third":3}
print(dic_arry)
print(dic_arry[2])
print(dic_arry["third"])
print(dic_arry[3])

{1: 'first', 2: 'second', 'third': 3}
second
3


KeyError: ignored

In [0]:
set_arry = set("hello")
print(set_arry)

{'h', 'e', 'l', 'o'}


## 4. 논리형(bool) 변수 입력 및 출력

In [0]:
c = True
type(c)

bool

## 5. 반복문 (for문, while문)

In [0]:
sum = 0
for i in range(10):
  sum += i
print(sum)

sum = 0
for i in range(1, 11):
  sum += i
print(sum)

45
55


In [0]:
treeHit = 0
while treeHit < 10:
    treeHit += 1
    print("나무를 %d번 찍었습니다" %treeHit)
    if treeHit == 10:
      print("나무가 넘어갑니다")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다


In [0]:
for j in list_arry_2:
  print(j)

5
2
[4, 6, 'abc', 'ddg']


## 6. 함수(def)와 클래스(class)

- def 함수이름(입력변수)
- class (여러 함수를 포함) 

In [0]:
money = 1000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

money = 2500
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

money = 10000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")

걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [0]:
def HowToGo(money):
  if money > 5000:
    print("택시를 타고 가자!")
  elif money > 1250:
    print("대중교통을 이용하자!")
  else:
    print("걸어가라...")

HowToGo(1000)
HowToGo(2500)
HowToGo(10000)


걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [0]:
class calculator:
  def __init__(self):
    self.result = 0
  
  def add(self, a, b):
    self.result = a + b
    return self.result
  
  def minus(self, a, b):
    self.result = a - b
    return self.result

cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


## 7. PyTorch 활용 

In [0]:
import torch

In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7630e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 4.5663e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.5776e-15]])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3331, 0.6766, 0.9304],
        [0.4236, 0.4139, 0.8850],
        [0.7973, 0.7905, 0.3437],
        [0.3048, 0.4822, 0.0535],
        [0.9999, 0.6594, 0.2771]])


In [0]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.4339, 0.7287, 0.5717, 0.0270],
        [0.2601, 0.4643, 0.3870, 0.9983],
        [0.6785, 0.7404, 0.0369, 0.1673]])
tensor([[0.4768, 0.3450, 0.9814, 0.6091],
        [0.3050, 0.1075, 0.1125, 0.9370],
        [0.9785, 0.3256, 0.6924, 0.1216]])
tensor([[0.9107, 1.0737, 1.5531, 0.6362],
        [0.5651, 0.5718, 0.4996, 1.9354],
        [1.6570, 1.0659, 0.7293, 0.2888]])
