In [1]:
a=100
print(a)
a=10.54
print(a)


100
10.54


In [2]:
b="this is string type"
print(b)
b="a"
print(b)

this is string type
a


In [3]:
list_arry = [1,4,6,"abc","ddg"]
print(list_arry)

[1, 4, 6, 'abc', 'ddg']


In [4]:
list_arry_2=[5,2,list_arry]
print(list_arry_2)

[5, 2, [1, 4, 6, 'abc', 'ddg']]


In [5]:
tuple_arry = (3,5,2,"gdd")
print(tuple_arry)

(3, 5, 2, 'gdd')


In [6]:
del tuple_arry[0]

TypeError: ignored

In [9]:
dic_arry = {1:"first", 2:"second", "third":3}
print(dic_arry)

{1: 'first', 2: 'second', 'third': 3}


In [10]:
print(dic_arry_3)

NameError: ignored

In [11]:
print(dic_arry["third"])

3


In [13]:
set_arry=set("heelo")
print(set_arry)

{'h', 'o', 'e', 'l'}


In [14]:
c = True
type(c)

bool

In [16]:
sum = 0
for i in range(10):
  sum += i
print(sum)

45


In [17]:
sum = 0
for i in range(1,11):
  sum += i
print(sum)

55


In [19]:
treeHit = 0
while treeHit < 10:
  treeHit += 1
  print("나무를 %d번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 1번 찍었습니다
나무를 2번 찍었습니다
나무를 3번 찍었습니다
나무를 4번 찍었습니다
나무를 5번 찍었습니다
나무를 6번 찍었습니다
나무를 7번 찍었습니다
나무를 8번 찍었습니다
나무를 9번 찍었습니다
나무를 10번 찍었습니다
나무가 넘어갑니다


In [20]:
for j in list_arry_2:
  print(j)

5
2
[1, 4, 6, 'abc', 'ddg']


In [21]:
money = 1000
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
  
money = 2500
if money > 5000:
  print("택시를 타고 가자!")
elif money > 1250:
  print("대중교통을 타고 가자!")
else:
  print("걸어가라...")

  
money = 10000
if money > 5000:
  print("택시를 타고 가자!")
elif money>1250:
  print("대중교통을 이용하자!")
else:
  print("걸어가라...")
    

걸어가라...
대중교통을 타고 가자!
택시를 타고 가자!


In [24]:
def HowToGo(money):
  if money > 5000:
    print("택시를 타고 가자!")
  elif money>1250:
    print("대중교통을 이용하자!")
  else:
    print("걸어가라...")
    
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)

걸어가라...
대중교통을 이용하자!
택시를 타고 가자!


In [28]:
class calculator:
  def __init__(self):
    self.result = 0
  
  def add(self, a, b):
    self.result = a + b
    return self.result
  
  def minus(self, a, b):
    self.result = a - b
    return self.result
  
cal = calculator()
  
print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [0]:
import torch

In [30]:
x=torch.empty(5,3)
print(x)

tensor([[3.8429e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.9097e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.5873e-43]])


In [31]:
x=torch.rand(5,3)
print(x)

tensor([[0.4901, 0.6412, 0.0765],
        [0.8111, 0.8914, 0.9917],
        [0.3977, 0.0580, 0.3113],
        [0.5900, 0.7808, 0.4208],
        [0.6949, 0.9458, 0.2844]])


In [32]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [33]:
x=torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [34]:
x=torch.rand(3,4)
y=torch.rand(3,4)
z=torch.add(x,y)
print(x,y,z, sep = "\n")

tensor([[0.5190, 0.0628, 0.0997, 0.8543],
        [0.0281, 0.0651, 0.2503, 0.5763],
        [0.9444, 0.0868, 0.8907, 0.1704]])
tensor([[0.7468, 0.2654, 0.1472, 0.4860],
        [0.9581, 0.4683, 0.4488, 0.3522],
        [0.8653, 0.8483, 0.2663, 0.1822]])
tensor([[1.2657, 0.3282, 0.2469, 1.3403],
        [0.9862, 0.5334, 0.6991, 0.9285],
        [1.8097, 0.9350, 1.1570, 0.3526]])
