<a href="https://colab.research.google.com/github/99robong/ai-security/blob/master/5th%20week/junoh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
a = 100
print(a)

a = 10.54
print(a)

100
10.54


In [0]:
b = "this is string type"
print(b)

b = 'a'
print(b)

this is string type
a


In [0]:
list_array = {1,4,6,"abc", "defg"}
print(list_array)

{1, 4, 6, 'abc', 'defg'}


In [0]:
list_array_2 = [5,2,list_array]
print(list_array_2)

[5, 2, {1, 4, 6, 'abc', 'defg'}]


In [0]:
tuple_array = (3,5,2,"gdd")
print(tuple_array)

(3, 5, 2, 'gdd')


In [0]:
del tuple_array[0]

TypeError: ignored

In [0]:
dic_arr = {1:"first", 2:"second", "third":3}
print(dic_arr)

{1: 'first', 2: 'second', 'third': 3}


In [0]:
print(dic_arr[3])

KeyError: ignored

In [0]:
print(dic_arr["third"])

3


In [0]:
set_array = set("hello")
print(set_array)

{'l', 'o', 'e', 'h'}


In [0]:
c = True
type(c)

bool

In [0]:
sum = 0
for i in range(10):
  sum += i
print(sum)

45


In [0]:
sum = 0
for i in range(1,11,2):
  sum += i
print(sum)

25


In [0]:
treeHit = 0
while treeHit < 10:
  treeHit += 1
  print("나무를 %d 번 찍었습니다" %treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")


나무를 1 번 찍었습니다
나무를 2 번 찍었습니다
나무를 3 번 찍었습니다
나무를 4 번 찍었습니다
나무를 5 번 찍었습니다
나무를 6 번 찍었습니다
나무를 7 번 찍었습니다
나무를 8 번 찍었습니다
나무를 9 번 찍었습니다
나무를 10 번 찍었습니다
나무가 넘어갑니다


In [0]:
for j in list_array_2:
  print(j)

5
2
{1, 4, 6, 'abc', 'defg'}


In [0]:
def HowToGo(money):
  if money > 5000:
    print("Taxi")
  elif money > 1250:
    print("대중교통")
  else:
    print("걸어가라...")
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)

걸어가라...
대중교통
Taxi


In [0]:
class calculator:
  def __init__(self):
    self.result = 0

  def add(self, a, b):
    self.result = a + b
    return self.result

  def minus(self, a, b):
    self.result = a - b
    return self.result
  
cal = calculator()

print(cal.add(4,5))
print(cal.minus(3,9))

9
-6


In [0]:
import torch

In [27]:
x = torch.empty(5,3)
print(x)

tensor([[1.1766e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [28]:
print(x)

tensor([[1.1766e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [0]:
x = torch.rand(5,3)

In [30]:
print(x)

tensor([[0.2737, 0.8958, 0.5031],
        [0.8091, 0.8820, 0.3934],
        [0.2826, 0.0388, 0.9392],
        [0.8013, 0.4683, 0.8187],
        [0.4961, 0.9639, 0.8347]])


In [31]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [33]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)
print(x,y,z, sep = "\n")

tensor([[0.3521, 0.6997, 0.9514, 0.3607],
        [0.2017, 0.3638, 0.4735, 0.0176],
        [0.8864, 0.3080, 0.7825, 0.6441]])
tensor([[0.3100, 0.0190, 0.7930, 0.2263],
        [0.9157, 0.5018, 0.2511, 0.4731],
        [0.8699, 0.3763, 0.9177, 0.7020]])
tensor([[0.6620, 0.7187, 1.7444, 0.5871],
        [1.1174, 0.8656, 0.7246, 0.4907],
        [1.7563, 0.6844, 1.7002, 1.3461]])
