<a href="https://colab.research.google.com/github/neonin04/ai-security/blob/master/5th%20week/SooIn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
sum=0
for i in range(10):
  sum += i
print(sum)

45


In [0]:
treeHit=0
while treeHit <10:
  treeHit += 1
  print("나무를 %d 번 찍었습니다", treeHit)
  if treeHit == 10:
    print("나무가 넘어갑니다")

나무를 %d 번 찍었습니다 1
나무를 %d 번 찍었습니다 2
나무를 %d 번 찍었습니다 3
나무를 %d 번 찍었습니다 4
나무를 %d 번 찍었습니다 5
나무를 %d 번 찍었습니다 6
나무를 %d 번 찍었습니다 7
나무를 %d 번 찍었습니다 8
나무를 %d 번 찍었습니다 9
나무를 %d 번 찍었습니다 10
나무가 넘어갑니다


In [0]:
def HowToGo(money):
  if money >5000:
    print("Taxi")
  elif money >1250:
    print("Transportation")
  else:
    print("Just Walk")
    
HowToGo(1000)
HowToGo(2500)
HowToGo(10000)

Just Walk
Transportation
Taxi


In [0]:
class calculator:
  def __init__(self):
    self.result = 0
    
  def add (self, a, b):
    self.result = a+b
    return self.result
  
  def minus (self, a, b):
    self.result = a-b
    return self.result
  
cal = calculator()

print(cal.add(1,2))
print(cal.minus(3,4))

3
-1


In [0]:
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[1.2671e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.9097e-19],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.5873e-43]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.6560, 0.6074, 0.4220],
        [0.7151, 0.1322, 0.4240],
        [0.6735, 0.9306, 0.4533],
        [0.2332, 0.3369, 0.0772],
        [0.6162, 0.2537, 0.7886]])


In [0]:
x = torch.rand(3,4)
y = torch.rand(3,4)
z = torch.add(x,y)

print(x,y,z, sep = "\n")

tensor([[0.6610, 0.2302, 0.7685, 0.3266],
        [0.3003, 0.3217, 0.6959, 0.1694],
        [0.4027, 0.9911, 0.0686, 0.9321]])
tensor([[0.6414, 0.9716, 0.5324, 0.4388],
        [0.3673, 0.1350, 0.3189, 0.8234],
        [0.3910, 0.2641, 0.7669, 0.4514]])
tensor([[1.3024, 1.2018, 1.3009, 0.7654],
        [0.6676, 0.4567, 1.0147, 0.9928],
        [0.7937, 1.2552, 0.8354, 1.3835]])
